// Generates addon/RoadToForever/PlanData.lua (ADDON_PLAN 15.5) from the site's own
// launch-plan.html (PLANS, PLAN_IDS, PHASES, and the override()/resolve() functions) and
// launch-plan-waypoints.json. build.py runs it; run_tests.py checks the checked-in file is
// up to date and compares the addon's plan filtering against the site's resolve().
//
// Usage:
//   node addon/tools/gen_plan_data.js            write addon/RoadToForever/PlanData.lua
//   node addon/tools/gen_plan_data.js --check    exit 1 if the file differs from a fresh generation
//   node addon/tools/gen_plan_data.js --expected print JSON: per plan, the ids + texts the SITE
//                                                shows (its resolve()), for the tests

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "..");
const OUT = path.join(root, "addon", "RoadToForever", "PlanData.lua");
const html = fs.readFileSync(path.join(root, "launch-plan.html"), "utf8");
const wpJson = JSON.parse(fs.readFileSync(path.join(root, "launch-plan-waypoints.json"), "utf8"));

// Only the launch-day phases (owner, 2026-10-09): not "before" (done before launch) or "beta".
const LAUNCH_PHASES = ["night", "p1", "p2", "p3"];

function grab(re, what) {
  const m = html.match(re);
  if (!m) throw new Error("gen_plan_data: could not find " + what + " in launch-plan.html");
  return m[0];
}

const siteCode = [
  grab(/^  var PLANS = \{[\s\S]*?^  \};$/m, "PLANS"),
  grab(/^  var PLAN_IDS = .*;$/m, "PLAN_IDS"),
  grab(/^  var PHASES = \{[\s\S]*?^  \};$/m, "PHASES"),
  grab(/^  function override\(item, plan\) \{[\s\S]*?^  \}$/m, "override()"),
  grab(/^  function resolve\(item, plan\) \{[\s\S]*?^  \}$/m, "resolve()"),
].join("\n");
const site = new Function(siteCode + "\nreturn { PLANS, PLAN_IDS, PHASES, resolve, override };")();

// Phase headings: the page's own <h2 id="p1">Phase 1 — 12 → 20</h2>.
function heading(id) {
  const m = html.match(new RegExp('<h2 id="' + id + '">([\\s\\S]*?)</h2>'));
  if (!m) throw new Error("gen_plan_data: no heading for " + id);
  return plain(m[1]);
}

// HTML (links, strong, em, entities) -> plain text for the game's font strings.
function plain(s) {
  s = String(s == null ? "" : s)
    .replace(/<br\s*\/?>/gi, " ")
    .replace(/<a\s[^>]*>([\s\S]*?)<\/a>/gi, "$1")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ").replace(/&times;/g, "x").replace(/&rarr;/g, "->")
    .replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&")
    .replace(/\s+/g, " ").trim();
  if (s.indexOf("|") !== -1) throw new Error("gen_plan_data: '|' in plan text (game escape char): " + s);
  return s;
}

function lstr(s) {
  return '"' + String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "")
    .replace(/[\x00-\x08\x0b-\x1f]/g, c => "\\" + String(c.charCodeAt(0)).padStart(3, "0")) + '"';
}
function lnum(n) { return String(n); }

function tagsLua(tags) {
  return "{ " + (tags || []).map(t => "{ " + lstr(t[0]) + ", " + lstr(plain(t[1])) + " }").join(", ") + " }";
}

function fieldsLua(o, keys) {
  const parts = [];
  for (const k of keys) {
    if (!(k in o)) continue;
    if (k === "tags") parts.push("tags = " + tagsLua(o.tags));
    else parts.push(k + " = " + lstr(plain(o[k])));
  }
  return parts.join(", ");
}

const FIELDS = ["lvl", "t", "n", "tags"];

function itemLua(item) {
  let s = "      { id = " + lstr(item.id);
  const base = fieldsLua(item, FIELDS);
  if (base) s += ", " + base;
  const ov = [];
  for (const p of site.PLAN_IDS) {
    if (!Object.prototype.hasOwnProperty.call(item, p)) continue;
    const o = item[p];
    ov.push(p + " = " + (o === false ? "false" : "{ " + fieldsLua(o, FIELDS) + " }"));
  }
  if (ov.length) s += ",\n        ov = { " + ov.join(", ") + " }";
  return s + " },";
}

function pointLua(p) {
  let s = "{ zone = " + lstr(p.zone);
  if (p.mapHint != null) s += ", mapHint = " + lnum(p.mapHint);
  if (p.x != null) s += ", x = " + lnum(p.x) + ", y = " + lnum(p.y);
  s += ", label = " + lstr(p.label) + ", conf = " + lstr(p.conf) + " }";
  return s;
}

function generate() {
  const ids = new Set();
  const out = [];
  out.push("-- PlanData.lua: the Launch Plan for the Plan tab (ADDON_PLAN 15.5).");
  out.push("-- GENERATED by addon/tools/gen_plan_data.js (run by build.py) from launch-plan.html (PLANS, PHASES)");
  out.push("-- and launch-plan-waypoints.json. Do not edit by hand: change the site data and rebuild.");
  out.push("-- Only the launch-day phases are here: " + LAUNCH_PHASES.join(", ") + ".");
  out.push("-- Item rules (same as the site): an item's own fields apply to every plan unless it has a");
  out.push("-- key in `ov` for that plan or for a plan up its `base` chain; `false` = hidden for that plan.");
  out.push("");
  out.push("local _, R2F = ...");
  out.push("");
  out.push("R2F.PlanData = {");
  out.push("  order = { " + site.PLAN_IDS.map(lstr).join(", ") + " },");
  out.push("  plans = {");
  for (const id of site.PLAN_IDS) {
    const p = site.PLANS[id];
    out.push("    " + id + " = { label = " + lstr(plain(p.label)) + ", short = " + lstr(plain(p.short)) +
      ", base = " + (p.base ? lstr(p.base) : "nil") + ", race = " + lstr(plain(p.race)) + ", extra = " + lstr(plain(p.extra)) + " },");
  }
  out.push("  },");
  out.push("  phases = {");
  for (const ph of LAUNCH_PHASES) {
    out.push("    { id = " + lstr(ph) + ", title = " + lstr(heading(ph)) + ", items = {");
    for (const item of site.PHASES[ph]) {
      if (ids.has(item.id)) throw new Error("gen_plan_data: duplicate step id " + item.id);
      ids.add(item.id);
      out.push(itemLua(item));
    }
    out.push("    } },");
  }
  out.push("  },");
  // Waypoints: step id -> { default = {points}, <plan> = {points} }.
  out.push("  waypoints = {");
  for (const id of Object.keys(wpJson.steps).sort()) {
    if (!ids.has(id)) throw new Error("gen_plan_data: waypoints for unknown or non-launch step " + id);
    const lists = wpJson.steps[id];
    const parts = [];
    for (const key of ["default"].concat(site.PLAN_IDS)) {
      if (!lists[key]) continue;
      parts.push(key + " = { " + lists[key].map(pointLua).join(", ") + " }");
    }
    for (const key of Object.keys(lists)) {
      if (key !== "default" && site.PLAN_IDS.indexOf(key) === -1) throw new Error("gen_plan_data: unknown plan key " + key + " for " + id);
    }
    out.push("    [" + lstr(id) + "] = { " + parts.join(", ") + " },");
  }
  out.push("  },");
  out.push("}");
  return out.join("\n") + "\n";
}

// What the site shows per plan (its own resolve()): ids and plain texts, in order.
function expected() {
  const res = {};
  for (const plan of site.PLAN_IDS) {
    res[plan] = [];
    for (const ph of LAUNCH_PHASES) {
      for (const item of site.PHASES[ph]) {
        const r = site.resolve(item, plan);
        if (!r) continue;
        res[plan].push({ phase: ph, id: r.id, lvl: plain(r.lvl), t: plain(r.t), n: plain(r.n || ""),
          tags: (r.tags || []).map(t => [t[0], plain(t[1])]) });
      }
    }
  }
  return { plans: res, phases: LAUNCH_PHASES, waypointSteps: Object.keys(wpJson.steps) };
}

const arg = process.argv[2];
if (arg === "--expected") {
  process.stdout.write(JSON.stringify(expected()));
} else if (arg === "--check") {
  const fresh = generate();
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (cur !== fresh) { console.error("PlanData.lua is out of date: run python build.py"); process.exit(1); }
} else {
  fs.writeFileSync(OUT, generate(), "utf8");
  console.log("PlanData.lua written");
}
